wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1659081582
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      4: 3.8.13
      5: 0.12.18
      8:
      - 2
      - 5
config:
  desc: null
  value: hr_larger
exp_name:
  desc: null
  value: hr_larger
lr:
  desc: null
  value: 0.04
